---
title: "Trying Trends"
author: "Daniel Shapiro"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
library(tidyverse)
library(readxl)
library(readr)
library(stringr)
library(data.table)
library(stats)
```

# Data read-in, changing NAs where it makes sense to

```{r}
stata <- read_xlsx("Full_dataset from STATA.xlsx") %>%
  filter(year != 2019)
stata$usaexport[is.na(stata$usaexport)] <- 0
stata$rusexp[is.na(stata$rusexp)] <- 0
stata$mil_aid_const[is.na(stata$mil_aid_const)] <- 0
stata$econ_aid_const[is.na(stata$econ_aid_const)] <- 0
stata$logUS[is.na(stata$logUS)] <- 0
stata$logRU[is.na(stata$logRU)] <- 0
stata$ru_growth[is.na(stata$ru_growth)] <- 0
stata$logmilaid[is.na(stata$logmilaid)] <- 0
stata$log_econ_aid[is.na(stata$log_econ_aid)] <- 0
```

```{r trends}

# Set up functions

doModel <- function(stata) lm(rusexp ~ year, stata)
democModel <- function(stata) lm(democ_score ~ year, stata)
milModel <- function(stata) lm(mil_aid_const ~ year, stata)
econModel <- function(stata) lm(econ_aid_const ~ year, stata)
idealModel <- function(stata) lm(idealpointdistance ~ year, stata)
getSlope <- function(mod) coef(mod)[2]

trends <- stata %>% 
  
# Run a ton of nesting and map functions to get trend lines for each country for each variable over the given time period.
  
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, doModel)) %>%
  mutate(arms_slope = map(model, getSlope)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(arms_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, milModel)) %>%
  mutate(mil_slope = map(model, getSlope)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(mil_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, econModel)) %>%
  mutate(econ_slope = map(model, getSlope)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(econ_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, democModel)) %>%
  mutate(democ_slope = map(model, getSlope)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(democ_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, idealModel)) %>%
  mutate(ideal_slope = map(model, getSlope)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(ideal_slope) %>%

# Now, we only need one year. I chose 2018, because why not. They should all have the same values.
  
  filter(year == 2018) %>%

# Select out the necessary variables 
  
  select(country, year, cow, arms_slope, econ_slope, mil_slope, ideal_slope, democ_slope) %>%

# Dividing slopes by 1,000,000 so it's more even
  
  mutate(econ_slope = (econ_slope/1000000)) %>%
  mutate(mil_slope = (mil_slope/1000000))
```

# Setting up regression

```{r}
regression <- lm(data = trends, formula = ideal_slope ~ arms_slope + econ_slope + mil_slope + democ_slope)

summary(regression)
```

# Seeing what happens during adversarial sanctions period

```{r}
sanctions <- read_xlsx("Full_dataset from STATA.xlsx") %>%
  filter(year %in% 2015:2018)
sanctions$usaexport[is.na(sanctions$usaexport)] <- 0
sanctions$rusexp[is.na(sanctions$rusexp)] <- 0
sanctions$mil_aid_const[is.na(sanctions$mil_aid_const)] <- 0
sanctions$econ_aid_const[is.na(sanctions$econ_aid_const)] <- 0
sanctions$logUS[is.na(sanctions$logUS)] <- 0
sanctions$logRU[is.na(sanctions$logRU)] <- 0
sanctions$ru_growth[is.na(sanctions$ru_growth)] <- 0
sanctions$logmilaid[is.na(sanctions$logmilaid)] <- 0
sanctions$log_econ_aid[is.na(sanctions$log_econ_aid)] <- 0

# Set up functions

doModel2 <- function(sanctions) lm(rusexp ~ year, sanctions)
democModel2 <- function(sanctions) lm(democ_score ~ year, sanctions)
milModel2 <- function(sanctions) lm(mil_aid_const ~ year, sanctions)
econModel2 <- function(sanctions) lm(econ_aid_const ~ year, sanctions)
idealModel2 <- function(sanctions) lm(idealpointdistance ~ year, sanctions)
getSlope2 <- function(mod) coef(mod)[2]

trends2 <- sanctions %>% 
  
# Run a ton of nesting and map functions to get trend lines for each country for each variable over the given time period.
  
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, doModel2)) %>%
  mutate(arms_slope = map(model, getSlope2)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(arms_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, milModel2)) %>%
  mutate(mil_slope = map(model, getSlope2)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(mil_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, econModel2)) %>%
  mutate(econ_slope = map(model, getSlope2)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(econ_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, democModel2)) %>%
  mutate(democ_slope = map(model, getSlope2)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(democ_slope) %>%
  group_by(country) %>%
  nest() %>%
  mutate(model = map(data, idealModel2)) %>%
  mutate(ideal_slope = map(model, getSlope2)) %>%
  unnest(data) %>%
  select(-model) %>%
  unnest(ideal_slope) %>%

# Now, we only need one year. I chose 2018, because why not. They should all have the same values.
  
  filter(year == 2018) %>%

# Select out the necessary variables 
  
  select(country, year, cow, arms_slope, econ_slope, mil_slope, ideal_slope, democ_slope) %>%

# Dividing slopes by 1,000,000 so it's more even
  
  mutate(econ_slope = (econ_slope/1000000)) %>%
  mutate(mil_slope = (mil_slope/1000000))
```

# Setting up second regression

```{r}
regression2 <- lm(data = trends2, formula = ideal_slope ~ arms_slope + econ_slope + mil_slope + democ_slope)

summary(regression2)

# This is not a good regression. 
```

