---
title: "US_Mil_Aid_Rec_St_Coop"
author: "Daniel Shapiro"
date: "1/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readr)
library(readxl)
library(stringr)
library(data.table)
library(stats)
```

## INDEPENDENT VARIABLE

# Data read-in

```{r data readin}
load("Dataset-Military-Aid-and-Recipient-State-Cooperation-091310 (4).RData")
x <- as_data_frame(x)

import <- read_csv("TIV-Import-All-2000-2019.csv", col_types = cols(
  .default = col_double(),
  Country = col_character()
))

usa <- read_csv("TIV-Export-USA-2000-2019.csv", col_types = cols(
  .default = col_double(),
  Country = col_character()
))

russia <- read_csv("TIV-Export-RUS-2000-2019.csv", col_types = cols(
  .default = col_double(),
  Country = col_character()
))

russia <- russia[-92, ]
usa <- usa[-130, ]
import <- import[-201, ]

russia <- russia %>% pivot_longer(`2000`:`2019`, names_to = "Year", values_to = "Russia") %>%
  select(-Total)

usa <- usa %>% pivot_longer(`2000`:`2019`, names_to = "Year", values_to = "USA") %>%
  select(-Total)

import <- import %>% pivot_longer(`2000`:`2019`, names_to = "Year", values_to = "Full") %>%
  select(-Total)

data <- merge(russia, usa, by = c("Country", "Year"), all = TRUE)
data[is.na(data)] <- 0

fulldata <- merge(data, import, by = c("Country", "Year"), all = TRUE)
fulldata[is.na(fulldata)] <- 0

# Full data column setup

fulldata <- fulldata %>% 
  mutate(RussiaPct = Russia/Full*100) %>%
  mutate(USPct = USA/Full*100)
fulldata[is.na(fulldata)] <- 0
```

# Finding Countries in Last 10 years with Presence of Both Russia and USA, then 2002-2010

```{r}
recent <- fulldata %>%
  filter(Year %in% c("2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"))  %>%
  filter(RussiaPct >= 2) %>%
  filter(USPct >= 2)
```

```{r}
recent <- recent[-c(72:81), ]
```

```{r}
recent
```

# Historic with linear regression

```{r}
historic <- fulldata %>%
  filter(Year %in% c("2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010"))

historic$Year = as.numeric(as.character(historic$Year))

# A LOT of basic linear regressions. I went through the data table, took a regression for each country that Russia sold to, looked at the slopes, and kept the ones that were positive.

Afghanistan <- historic[1:9, ]
lm(data = Afghanistan, formula = Russia ~ Year)

Algeria <- historic[28:36, ]
lm(data = Algeria, formula = Russia ~ Year)

Armenia <- historic[55:63, ]
lm(data = Armenia, formula = Russia ~ Year)

Azerbaijan <- historic[82:90, ]
lm(data = Azerbaijan, formula = Russia ~ Year)

Brazil <- historic[190:198, ]
lm(data = Brazil, formula = Russia ~ Year)

Chad <- historic[280:288, ]
lm(data = Chad, formula = Russia ~ Year)

Croatia <- historic[352:360, ]
lm(data = Croatia, formula = Russia ~ Year)

Cyprus <- historic[370:378, ]
lm(data = Cyprus, formula = Russia ~ Year)

Ecuador <- historic[433:441, ]
lm(data = Ecuador, formula = Russia ~ Year)

Egypt <- historic[442:450, ]
lm(data = Egypt, formula = Russia ~ Year)

India <- historic[667:675, ]
lm(data = India, formula = Russia ~ Year)

Indonesia <- historic[676:684, ]
lm(data = Indonesia, formula = Russia ~ Year)

Iraq <- historic[694:702, ]
lm(data = Iraq, formula = Russia ~ Year)

Jordan <- historic[748:756, ]
lm(data = Jordan, formula = Russia ~ Year)

Kazakhstan <- historic[757:765, ]
lm(data = Kazakhstan, formula = Russia ~ Year)

Kenya <- historic[766:774, ]
lm(data = Kenya, formula = Russia ~ Year)

Kuwait <- historic[784:792, ]
lm(data = Kuwait, formula = Russia ~ Year)

Libya <- historic[847:855, ]
lm(data = Libya, formula = Russia ~ Year)

Malaysia <- historic[937:945, ]
lm(data = Malaysia, formula = Russia ~ Year)

Mexico <- historic[991:999, ]
lm(data = Mexico, formula = Russia ~ Year)

Mongolia <- historic[1000:1008, ]
lm(data = Mongolia, formula = Russia ~ Year)

Morocco <- historic[1018:1026, ]
lm(data = Morocco, formula = Russia ~ Year)

Nicaragua <- historic[1090:1098, ]
lm(data = Nicaragua, formula = Russia ~ Year)

Niger <- historic[1099:1107, ]
lm(data = Niger, formula = Russia ~ Year)

Peru <- historic[1225:1233, ]
lm(data = Peru, formula = Russia ~ Year)

Poland <- historic[1261:1269, ]
lm(data = Poland, formula = Russia ~ Year)

Senegal <- historic[1342:1350, ]
lm(data = Senegal, formula = Russia ~ Year)

Slovenia <- historic[1396:1404, ]
lm(data = Slovenia, formula = Russia ~ Year)

Syria <- historic[1504:1512, ]
lm(data = Syria, formula = Russia ~ Year)

Tajikistan <- historic[1531:1539, ]
lm(data = Tajikistan, formula = Russia ~ Year)

Thailand <- historic[1549:1557, ]
lm(data = Thailand, formula = Russia ~ Year)

Turkey <- historic[1612:1620, ]
lm(data = Turkey, formula = Russia ~ Year)

Turkmenistan <- historic[1621:1629, ]
lm(data = Turkmenistan, formula = Russia ~ Year)

UAE <- historic[1639:1647, ]
lm(data = UAE, formula = Russia ~ Year)

Uzbekistan <- historic[1747:1755, ]
lm(data = Uzbekistan, formula = Russia ~ Year)

Venezuela <- historic[1756:1764, ]
lm(data = Venezuela, formula = Russia ~ Year)

Vietnam <- historic[1765:1773, ]
lm(data = Vietnam, formula = Russia ~ Year)
```

# Filtering Countries from previous category into U.S. aid data (dataframe x); writing to new CSV for further use in Excel

```{r}
specific <- x %>% filter(ccodesrc %in% c(692, 771, 140, 651, 750, 645, 663, 690, 475, 770, 135, 800, 640, 696, 704))

specific <- specific[ ,1:19]

write.csv(specific, "specific.csv", row.names = FALSE)
```

## DEPENDENT VARIABLE

# Reading in and messing with DCAD data

```{r}
dcadmain <- read_csv("DCAD-v1.0-main.csv", col_types = cols(
  .default = col_double(),
  cowName1 = col_character(),
  cowName2 = col_character(),
  type = col_character(),
  category1 = col_character(),
  category2 = col_character(),
  category3 = col_character(),
  categoryConf = col_character(),
  fullText = col_character(),
  sourceType = col_character(),
  source = col_character(),
  DCAid = col_character()
)) %>%
  filter(cowName1 %in% c("USA", "RUS"))
```

```{r}
dyadic <- read_csv("DCAD-v1.0-dyadic.csv", col_types = cols(
  ccode1 = col_double(),
  abbrev1 = col_character(),
  ccode2 = col_double(),
  abbrev2 = col_character(),
  year = col_double(),
  dcaGeneralV1 = col_double(),
  dcaGeneralV2 = col_double(),
  dcaSectorV1 = col_double(),
  dcaSectorV2 = col_double(),
  dcaAnyV1 = col_double(),
  dcaAnyV2 = col_double()
)) %>%
  filter(year %in% c(1991:2010)) %>%
  filter(abbrev1 %in% c("USA", "RUS"))
```

# Opening and Reading in Polity V Scores

```{r}
polity <- read_xls("p5v2018.xls") 
```

```{r}
polity <- polity %>%
  filter(year %in% c("1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018")) %>%
  filter(country %in% c("Peru", "Brazil", "Nigeria", "Turkey", "Iraq", "Egypt", "Jordan", "Kuwait", "Bahrain", "UAE", "Uzbekistan", "India", "Pakistan", "Bangladesh", "Thailand")) %>%
  select(c(country, year, polity2))

write.csv(polity, "polity.csv", row.names = FALSE)
```